use practicedb;
create table PLAN(
PLAN_AMNT int(6) NOT NULL,
VALIDITY_INDAYS int(4),
LOCAL_VOICE_INMINS_PERDAY_SN int(3),
LOCAL_VOICE_INMINS_PERDAY_ON int(3),
STD_VOICE_INMINS_PERDAY_SN int(3),
STD_VOICE_INMINS_PERDAY_ON int(3),
DATA_INGB_PERDAY DOUBLE(3,1),
SMS_PERDAY int(3),
PLAN_TYPE VARCHAR(10),
primary key(PLAN_AMNT));

create table CUSTOMER(
PHN_NO VARCHAR(10),
CUSTOMER_NAME VARCHAR(20),
EMAIL_ID VARCHAR(35),
ADDRESS VARCHAR(50),
primary key(PHN_NO));


create table SUBSCRIPTION(
PHN_NO varchar(10),
PLAN_AMNT int(6),
RECHARGE_DATE date,
EXPIRY_DATE date,
foreign key (PLAN_AMNT) references PLAN(PLAN_AMNT),
foreign key(PHN_NO) references CUSTOMER(PHN_NO));


desc SUBSCRIPTION;
desc CUSTOMER;
DESC PLAN;